### ISSUE TITLE
[BABEL] /node_modules/@babel/compat-data/data/corejs3-shipped-proposals'

### ISSUE THREAD

**Issue by antoinebeneteau** [ammarjabakji/gatsby-markdown-blog-starter#1]

**Comment by alexgonch** [comment]
I'm guessing you ran into a build error like this one:

```
[BABEL] /usr/src/app/www/.cache/production-app.js: Cannot find module '/usr/src/app/www/node_modules/@babel/compat-data/data/corejs3-shipped-proposals'
```

I got it too and fixed it by updating the babel plugin: `npm update --depth 5 @babel/compat-data`

Might be helpful for other people trying to run this project.

**Comment by ammarjabakji** [comment]
Thank you, Alex,
Yes some times you need to update all packages to solve these type of issues 
You may try;

`npm outdated`
`npm update --save/--save-dev`

And don't forget to delete the .cache folder
